### ISSUE TITLE
no recipe for u-boot-adi (without version or %) on v0.5-rc4

### ISSUE THREAD

**Issue by elytone-denny-chang** [analogdevicesinc/ADSP-UCSDK#1]
![image](https://user-images.githubusercontent.com/71483510/196618881-4845f6dd-9559-4066-bf1b-822c04740cb1.png)

**Comment by harvinb** [comment]
Hi Denny,
Did you use the install script to setup the layer?

**Comment by elytone-denny-chang** [comment]
No, I use git submodule to clone whole one instead of use install from ucsdk. It's easier to management build system for me.

**Comment by harvinb** [comment]
Hi Denny, 
Currently this layer supports different versions of ADI Yocto for different ADSP-SC5xx boards. The install script I mentioned removes some recipe files depending on the board and ADI Yocto version. If you are using git submodule, I suggest you refer the install script see which files are removed and have a script that removes the same files.

**Comment by elytone-denny-chang** [comment]
understand it. I will fork it to create a modification branch for my submodule usage.
